FROM python:3.12-slim
WORKDIR /srv
COPY shared/ /shared/
RUN pip install --no-cache-dir -e /shared
COPY alembic/ alembic/
COPY alembic.ini .
RUN pip install --no-cache-dir alembic asyncpg pyyaml
CMD ["alembic", "upgrade", "head"]
