"""initial

Revision ID: dd18b3670e2a
Revises: 
Create Date: 2026-03-17 16:55:01.572665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd18b3670e2a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('game_settings',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('initial_balance', sa.Integer(), nullable=False),
    sa.Column('target_balance', sa.Integer(), nullable=False),
    sa.Column('bet_amount', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('LOBBY', 'PLAYING', 'FINISHED', name='gamestatus'), nullable=False),
    sa.Column('lobby_expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_chat_id'), 'games', ['chat_id'], unique=False)
    op.create_table('players',
    sa.Column('vk_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('vk_id')
    )
    op.create_table('game_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('hand', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.vk_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('dealer_hand', sa.JSON(), nullable=False),
    sa.Column('current_player_index', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DEALING', 'PLAYER_TURN', 'DEALER_TURN', 'FINISHED', name='roundstatus'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_rounds')
    op.drop_table('game_players')
    op.drop_table('players')
    op.drop_index(op.f('ix_games_chat_id'), table_name='games')
    op.drop_table('games')
    op.drop_table('game_settings')
    op.drop_table('admins')
    # ### end Alembic commands ###
